### PR TITLE
Second revision

### PR DESCRIPTION
**Pull request by nevtay**
**JS Changes**

- Removed `const inputEl.placeholder`
- Merged `hideConversions()` and `showConversions()` into `toggleOutputDisplay()`;
- Added weight ratios

**CSS Changes**

- added `.hidden` class

**HTML Changes**

> Change weight unit

 is now 

> Current weight unit

### CODE REVIEW

**Comment by spbsamuel** [comment]
So what people normally do is work on one pr. So instead of doing revision two you add the changes to revision one. and when revision one is good to go the reviewer approves it and you merge it in. 

I am trying to introduce you to these workflows because this is kinda how its done in the industry. But if you prefer not to we can stick to just looking at code

**Comment by nevtay** [comment]
> I am trying to introduce you to these workflows because this is kinda how its done in the industry. But if you prefer not to we can stick to just looking at code

I'll take industry standards!

**Comment by spbsamuel** [comment]
Okay can you merge second-revision into first-revision. Try doing it in ur terminal as practice. Then close this pr and delete the branch.

**Comment by nevtay** [comment]
Merge was successful on my end. Any issue viewing the changes?

**Pull request closed without merging**
